# Generated by Django 5.1.4 on 2024-12-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('json_data', models.TextField()),
            ],
        ),
    ]
